// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package org.jmotor.metral.dto;

public interface FireChangedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jmotor.metral.dto.FireChanged)
    com.github.os72.protobuf360.MessageOrBuilder {

  /**
   * <code>string entity = 1;</code>
   */
  java.lang.String getEntity();
  /**
   * <code>string entity = 1;</code>
   */
  com.github.os72.protobuf360.ByteString
      getEntityBytes();

  /**
   * <code>string identity = 2;</code>
   */
  java.lang.String getIdentity();
  /**
   * <code>string identity = 2;</code>
   */
  com.github.os72.protobuf360.ByteString
      getIdentityBytes();

  /**
   * <code>.org.jmotor.metral.dto.Operation operation = 3;</code>
   */
  int getOperationValue();
  /**
   * <code>.org.jmotor.metral.dto.Operation operation = 3;</code>
   */
  org.jmotor.metral.dto.Operation getOperation();

  /**
   * <code>int64 timestamp = 4;</code>
   */
  long getTimestamp();
}
