// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package org.jmotor.metral.dto;

/**
 * Protobuf type {@code org.jmotor.metral.dto.FireChanged}
 */
public  final class FireChanged extends
    com.github.os72.protobuf360.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.jmotor.metral.dto.FireChanged)
    FireChangedOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FireChanged.newBuilder() to construct.
  private FireChanged(com.github.os72.protobuf360.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FireChanged() {
    entity_ = "";
    identity_ = com.github.os72.protobuf360.ByteString.EMPTY;
    operation_ = 0;
    timestamp_ = 0L;
  }

  @java.lang.Override
  public final com.github.os72.protobuf360.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FireChanged(
      com.github.os72.protobuf360.CodedInputStream input,
      com.github.os72.protobuf360.ExtensionRegistryLite extensionRegistry)
      throws com.github.os72.protobuf360.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.github.os72.protobuf360.UnknownFieldSet.Builder unknownFields =
        com.github.os72.protobuf360.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            entity_ = s;
            break;
          }
          case 18: {

            identity_ = input.readBytes();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            operation_ = rawValue;
            break;
          }
          case 32: {

            timestamp_ = input.readInt64();
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              attributes_ = com.github.os72.protobuf360.MapField.newMapField(
                  AttributesDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000010;
            }
            com.github.os72.protobuf360.MapEntry<java.lang.String, com.github.os72.protobuf360.ByteString>
            attributes__ = input.readMessage(
                AttributesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            attributes_.getMutableMap().put(
                attributes__.getKey(), attributes__.getValue());
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.github.os72.protobuf360.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.github.os72.protobuf360.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.github.os72.protobuf360.Descriptors.Descriptor
      getDescriptor() {
    return org.jmotor.metral.dto.MetralMessages.internal_static_org_jmotor_metral_dto_FireChanged_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.github.os72.protobuf360.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 5:
        return internalGetAttributes();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.github.os72.protobuf360.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.jmotor.metral.dto.MetralMessages.internal_static_org_jmotor_metral_dto_FireChanged_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.jmotor.metral.dto.FireChanged.class, org.jmotor.metral.dto.FireChanged.Builder.class);
  }

  private int bitField0_;
  public static final int ENTITY_FIELD_NUMBER = 1;
  private volatile java.lang.Object entity_;
  /**
   * <code>string entity = 1;</code>
   */
  public java.lang.String getEntity() {
    java.lang.Object ref = entity_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.github.os72.protobuf360.ByteString bs = 
          (com.github.os72.protobuf360.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      entity_ = s;
      return s;
    }
  }
  /**
   * <code>string entity = 1;</code>
   */
  public com.github.os72.protobuf360.ByteString
      getEntityBytes() {
    java.lang.Object ref = entity_;
    if (ref instanceof java.lang.String) {
      com.github.os72.protobuf360.ByteString b = 
          com.github.os72.protobuf360.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      entity_ = b;
      return b;
    } else {
      return (com.github.os72.protobuf360.ByteString) ref;
    }
  }

  public static final int IDENTITY_FIELD_NUMBER = 2;
  private com.github.os72.protobuf360.ByteString identity_;
  /**
   * <code>bytes identity = 2;</code>
   */
  public com.github.os72.protobuf360.ByteString getIdentity() {
    return identity_;
  }

  public static final int OPERATION_FIELD_NUMBER = 3;
  private int operation_;
  /**
   * <code>.org.jmotor.metral.dto.Operation operation = 3;</code>
   */
  public int getOperationValue() {
    return operation_;
  }
  /**
   * <code>.org.jmotor.metral.dto.Operation operation = 3;</code>
   */
  public org.jmotor.metral.dto.Operation getOperation() {
    @SuppressWarnings("deprecation")
    org.jmotor.metral.dto.Operation result = org.jmotor.metral.dto.Operation.valueOf(operation_);
    return result == null ? org.jmotor.metral.dto.Operation.UNRECOGNIZED : result;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 4;
  private long timestamp_;
  /**
   * <code>int64 timestamp = 4;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int ATTRIBUTES_FIELD_NUMBER = 5;
  private static final class AttributesDefaultEntryHolder {
    static final com.github.os72.protobuf360.MapEntry<
        java.lang.String, com.github.os72.protobuf360.ByteString> defaultEntry =
            com.github.os72.protobuf360.MapEntry
            .<java.lang.String, com.github.os72.protobuf360.ByteString>newDefaultInstance(
                org.jmotor.metral.dto.MetralMessages.internal_static_org_jmotor_metral_dto_FireChanged_AttributesEntry_descriptor, 
                com.github.os72.protobuf360.WireFormat.FieldType.STRING,
                "",
                com.github.os72.protobuf360.WireFormat.FieldType.BYTES,
                com.github.os72.protobuf360.ByteString.EMPTY);
  }
  private com.github.os72.protobuf360.MapField<
      java.lang.String, com.github.os72.protobuf360.ByteString> attributes_;
  private com.github.os72.protobuf360.MapField<java.lang.String, com.github.os72.protobuf360.ByteString>
  internalGetAttributes() {
    if (attributes_ == null) {
      return com.github.os72.protobuf360.MapField.emptyMapField(
          AttributesDefaultEntryHolder.defaultEntry);
    }
    return attributes_;
  }

  public int getAttributesCount() {
    return internalGetAttributes().getMap().size();
  }
  /**
   * <code>map&lt;string, bytes&gt; attributes = 5;</code>
   */

  public boolean containsAttributes(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetAttributes().getMap().containsKey(key);
  }
  /**
   * Use {@link #getAttributesMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.github.os72.protobuf360.ByteString> getAttributes() {
    return getAttributesMap();
  }
  /**
   * <code>map&lt;string, bytes&gt; attributes = 5;</code>
   */

  public java.util.Map<java.lang.String, com.github.os72.protobuf360.ByteString> getAttributesMap() {
    return internalGetAttributes().getMap();
  }
  /**
   * <code>map&lt;string, bytes&gt; attributes = 5;</code>
   */

  public com.github.os72.protobuf360.ByteString getAttributesOrDefault(
      java.lang.String key,
      com.github.os72.protobuf360.ByteString defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.github.os72.protobuf360.ByteString> map =
        internalGetAttributes().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, bytes&gt; attributes = 5;</code>
   */

  public com.github.os72.protobuf360.ByteString getAttributesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.github.os72.protobuf360.ByteString> map =
        internalGetAttributes().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.github.os72.protobuf360.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getEntityBytes().isEmpty()) {
      com.github.os72.protobuf360.GeneratedMessageV3.writeString(output, 1, entity_);
    }
    if (!identity_.isEmpty()) {
      output.writeBytes(2, identity_);
    }
    if (operation_ != org.jmotor.metral.dto.Operation.CREATE.getNumber()) {
      output.writeEnum(3, operation_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(4, timestamp_);
    }
    com.github.os72.protobuf360.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetAttributes(),
        AttributesDefaultEntryHolder.defaultEntry,
        5);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getEntityBytes().isEmpty()) {
      size += com.github.os72.protobuf360.GeneratedMessageV3.computeStringSize(1, entity_);
    }
    if (!identity_.isEmpty()) {
      size += com.github.os72.protobuf360.CodedOutputStream
        .computeBytesSize(2, identity_);
    }
    if (operation_ != org.jmotor.metral.dto.Operation.CREATE.getNumber()) {
      size += com.github.os72.protobuf360.CodedOutputStream
        .computeEnumSize(3, operation_);
    }
    if (timestamp_ != 0L) {
      size += com.github.os72.protobuf360.CodedOutputStream
        .computeInt64Size(4, timestamp_);
    }
    for (java.util.Map.Entry<java.lang.String, com.github.os72.protobuf360.ByteString> entry
         : internalGetAttributes().getMap().entrySet()) {
      com.github.os72.protobuf360.MapEntry<java.lang.String, com.github.os72.protobuf360.ByteString>
      attributes__ = AttributesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.github.os72.protobuf360.CodedOutputStream
          .computeMessageSize(5, attributes__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.jmotor.metral.dto.FireChanged)) {
      return super.equals(obj);
    }
    org.jmotor.metral.dto.FireChanged other = (org.jmotor.metral.dto.FireChanged) obj;

    boolean result = true;
    result = result && getEntity()
        .equals(other.getEntity());
    result = result && getIdentity()
        .equals(other.getIdentity());
    result = result && operation_ == other.operation_;
    result = result && (getTimestamp()
        == other.getTimestamp());
    result = result && internalGetAttributes().equals(
        other.internalGetAttributes());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENTITY_FIELD_NUMBER;
    hash = (53 * hash) + getEntity().hashCode();
    hash = (37 * hash) + IDENTITY_FIELD_NUMBER;
    hash = (53 * hash) + getIdentity().hashCode();
    hash = (37 * hash) + OPERATION_FIELD_NUMBER;
    hash = (53 * hash) + operation_;
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.github.os72.protobuf360.Internal.hashLong(
        getTimestamp());
    if (!internalGetAttributes().getMap().isEmpty()) {
      hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetAttributes().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.jmotor.metral.dto.FireChanged parseFrom(
      java.nio.ByteBuffer data)
      throws com.github.os72.protobuf360.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jmotor.metral.dto.FireChanged parseFrom(
      java.nio.ByteBuffer data,
      com.github.os72.protobuf360.ExtensionRegistryLite extensionRegistry)
      throws com.github.os72.protobuf360.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jmotor.metral.dto.FireChanged parseFrom(
      com.github.os72.protobuf360.ByteString data)
      throws com.github.os72.protobuf360.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jmotor.metral.dto.FireChanged parseFrom(
      com.github.os72.protobuf360.ByteString data,
      com.github.os72.protobuf360.ExtensionRegistryLite extensionRegistry)
      throws com.github.os72.protobuf360.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jmotor.metral.dto.FireChanged parseFrom(byte[] data)
      throws com.github.os72.protobuf360.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jmotor.metral.dto.FireChanged parseFrom(
      byte[] data,
      com.github.os72.protobuf360.ExtensionRegistryLite extensionRegistry)
      throws com.github.os72.protobuf360.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jmotor.metral.dto.FireChanged parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.github.os72.protobuf360.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.jmotor.metral.dto.FireChanged parseFrom(
      java.io.InputStream input,
      com.github.os72.protobuf360.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.github.os72.protobuf360.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.jmotor.metral.dto.FireChanged parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.github.os72.protobuf360.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.jmotor.metral.dto.FireChanged parseDelimitedFrom(
      java.io.InputStream input,
      com.github.os72.protobuf360.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.github.os72.protobuf360.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.jmotor.metral.dto.FireChanged parseFrom(
      com.github.os72.protobuf360.CodedInputStream input)
      throws java.io.IOException {
    return com.github.os72.protobuf360.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.jmotor.metral.dto.FireChanged parseFrom(
      com.github.os72.protobuf360.CodedInputStream input,
      com.github.os72.protobuf360.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.github.os72.protobuf360.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.jmotor.metral.dto.FireChanged prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.github.os72.protobuf360.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.jmotor.metral.dto.FireChanged}
   */
  public static final class Builder extends
      com.github.os72.protobuf360.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.jmotor.metral.dto.FireChanged)
      org.jmotor.metral.dto.FireChangedOrBuilder {
    public static final com.github.os72.protobuf360.Descriptors.Descriptor
        getDescriptor() {
      return org.jmotor.metral.dto.MetralMessages.internal_static_org_jmotor_metral_dto_FireChanged_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.github.os72.protobuf360.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetAttributes();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.github.os72.protobuf360.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetMutableAttributes();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.github.os72.protobuf360.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jmotor.metral.dto.MetralMessages.internal_static_org_jmotor_metral_dto_FireChanged_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.jmotor.metral.dto.FireChanged.class, org.jmotor.metral.dto.FireChanged.Builder.class);
    }

    // Construct using org.jmotor.metral.dto.FireChanged.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.github.os72.protobuf360.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.github.os72.protobuf360.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      entity_ = "";

      identity_ = com.github.os72.protobuf360.ByteString.EMPTY;

      operation_ = 0;

      timestamp_ = 0L;

      internalGetMutableAttributes().clear();
      return this;
    }

    @java.lang.Override
    public com.github.os72.protobuf360.Descriptors.Descriptor
        getDescriptorForType() {
      return org.jmotor.metral.dto.MetralMessages.internal_static_org_jmotor_metral_dto_FireChanged_descriptor;
    }

    @java.lang.Override
    public org.jmotor.metral.dto.FireChanged getDefaultInstanceForType() {
      return org.jmotor.metral.dto.FireChanged.getDefaultInstance();
    }

    @java.lang.Override
    public org.jmotor.metral.dto.FireChanged build() {
      org.jmotor.metral.dto.FireChanged result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.jmotor.metral.dto.FireChanged buildPartial() {
      org.jmotor.metral.dto.FireChanged result = new org.jmotor.metral.dto.FireChanged(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.entity_ = entity_;
      result.identity_ = identity_;
      result.operation_ = operation_;
      result.timestamp_ = timestamp_;
      result.attributes_ = internalGetAttributes();
      result.attributes_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.github.os72.protobuf360.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.github.os72.protobuf360.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.github.os72.protobuf360.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.github.os72.protobuf360.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.github.os72.protobuf360.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.github.os72.protobuf360.Message other) {
      if (other instanceof org.jmotor.metral.dto.FireChanged) {
        return mergeFrom((org.jmotor.metral.dto.FireChanged)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.jmotor.metral.dto.FireChanged other) {
      if (other == org.jmotor.metral.dto.FireChanged.getDefaultInstance()) return this;
      if (!other.getEntity().isEmpty()) {
        entity_ = other.entity_;
        onChanged();
      }
      if (other.getIdentity() != com.github.os72.protobuf360.ByteString.EMPTY) {
        setIdentity(other.getIdentity());
      }
      if (other.operation_ != 0) {
        setOperationValue(other.getOperationValue());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      internalGetMutableAttributes().mergeFrom(
          other.internalGetAttributes());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.github.os72.protobuf360.CodedInputStream input,
        com.github.os72.protobuf360.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.jmotor.metral.dto.FireChanged parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.github.os72.protobuf360.InvalidProtocolBufferException e) {
        parsedMessage = (org.jmotor.metral.dto.FireChanged) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object entity_ = "";
    /**
     * <code>string entity = 1;</code>
     */
    public java.lang.String getEntity() {
      java.lang.Object ref = entity_;
      if (!(ref instanceof java.lang.String)) {
        com.github.os72.protobuf360.ByteString bs =
            (com.github.os72.protobuf360.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        entity_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string entity = 1;</code>
     */
    public com.github.os72.protobuf360.ByteString
        getEntityBytes() {
      java.lang.Object ref = entity_;
      if (ref instanceof String) {
        com.github.os72.protobuf360.ByteString b = 
            com.github.os72.protobuf360.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entity_ = b;
        return b;
      } else {
        return (com.github.os72.protobuf360.ByteString) ref;
      }
    }
    /**
     * <code>string entity = 1;</code>
     */
    public Builder setEntity(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      entity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string entity = 1;</code>
     */
    public Builder clearEntity() {
      
      entity_ = getDefaultInstance().getEntity();
      onChanged();
      return this;
    }
    /**
     * <code>string entity = 1;</code>
     */
    public Builder setEntityBytes(
        com.github.os72.protobuf360.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      entity_ = value;
      onChanged();
      return this;
    }

    private com.github.os72.protobuf360.ByteString identity_ = com.github.os72.protobuf360.ByteString.EMPTY;
    /**
     * <code>bytes identity = 2;</code>
     */
    public com.github.os72.protobuf360.ByteString getIdentity() {
      return identity_;
    }
    /**
     * <code>bytes identity = 2;</code>
     */
    public Builder setIdentity(com.github.os72.protobuf360.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      identity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes identity = 2;</code>
     */
    public Builder clearIdentity() {
      
      identity_ = getDefaultInstance().getIdentity();
      onChanged();
      return this;
    }

    private int operation_ = 0;
    /**
     * <code>.org.jmotor.metral.dto.Operation operation = 3;</code>
     */
    public int getOperationValue() {
      return operation_;
    }
    /**
     * <code>.org.jmotor.metral.dto.Operation operation = 3;</code>
     */
    public Builder setOperationValue(int value) {
      operation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.org.jmotor.metral.dto.Operation operation = 3;</code>
     */
    public org.jmotor.metral.dto.Operation getOperation() {
      @SuppressWarnings("deprecation")
      org.jmotor.metral.dto.Operation result = org.jmotor.metral.dto.Operation.valueOf(operation_);
      return result == null ? org.jmotor.metral.dto.Operation.UNRECOGNIZED : result;
    }
    /**
     * <code>.org.jmotor.metral.dto.Operation operation = 3;</code>
     */
    public Builder setOperation(org.jmotor.metral.dto.Operation value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      operation_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.org.jmotor.metral.dto.Operation operation = 3;</code>
     */
    public Builder clearOperation() {
      
      operation_ = 0;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 4;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 4;</code>
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 4;</code>
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private com.github.os72.protobuf360.MapField<
        java.lang.String, com.github.os72.protobuf360.ByteString> attributes_;
    private com.github.os72.protobuf360.MapField<java.lang.String, com.github.os72.protobuf360.ByteString>
    internalGetAttributes() {
      if (attributes_ == null) {
        return com.github.os72.protobuf360.MapField.emptyMapField(
            AttributesDefaultEntryHolder.defaultEntry);
      }
      return attributes_;
    }
    private com.github.os72.protobuf360.MapField<java.lang.String, com.github.os72.protobuf360.ByteString>
    internalGetMutableAttributes() {
      onChanged();;
      if (attributes_ == null) {
        attributes_ = com.github.os72.protobuf360.MapField.newMapField(
            AttributesDefaultEntryHolder.defaultEntry);
      }
      if (!attributes_.isMutable()) {
        attributes_ = attributes_.copy();
      }
      return attributes_;
    }

    public int getAttributesCount() {
      return internalGetAttributes().getMap().size();
    }
    /**
     * <code>map&lt;string, bytes&gt; attributes = 5;</code>
     */

    public boolean containsAttributes(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAttributes().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAttributesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.github.os72.protobuf360.ByteString> getAttributes() {
      return getAttributesMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; attributes = 5;</code>
     */

    public java.util.Map<java.lang.String, com.github.os72.protobuf360.ByteString> getAttributesMap() {
      return internalGetAttributes().getMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; attributes = 5;</code>
     */

    public com.github.os72.protobuf360.ByteString getAttributesOrDefault(
        java.lang.String key,
        com.github.os72.protobuf360.ByteString defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.github.os72.protobuf360.ByteString> map =
          internalGetAttributes().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, bytes&gt; attributes = 5;</code>
     */

    public com.github.os72.protobuf360.ByteString getAttributesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.github.os72.protobuf360.ByteString> map =
          internalGetAttributes().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearAttributes() {
      internalGetMutableAttributes().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, bytes&gt; attributes = 5;</code>
     */

    public Builder removeAttributes(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableAttributes().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.github.os72.protobuf360.ByteString>
    getMutableAttributes() {
      return internalGetMutableAttributes().getMutableMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; attributes = 5;</code>
     */
    public Builder putAttributes(
        java.lang.String key,
        com.github.os72.protobuf360.ByteString value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableAttributes().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, bytes&gt; attributes = 5;</code>
     */

    public Builder putAllAttributes(
        java.util.Map<java.lang.String, com.github.os72.protobuf360.ByteString> values) {
      internalGetMutableAttributes().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.github.os72.protobuf360.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.github.os72.protobuf360.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.jmotor.metral.dto.FireChanged)
  }

  // @@protoc_insertion_point(class_scope:org.jmotor.metral.dto.FireChanged)
  private static final org.jmotor.metral.dto.FireChanged DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.jmotor.metral.dto.FireChanged();
  }

  public static org.jmotor.metral.dto.FireChanged getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.github.os72.protobuf360.Parser<FireChanged>
      PARSER = new com.github.os72.protobuf360.AbstractParser<FireChanged>() {
    @java.lang.Override
    public FireChanged parsePartialFrom(
        com.github.os72.protobuf360.CodedInputStream input,
        com.github.os72.protobuf360.ExtensionRegistryLite extensionRegistry)
        throws com.github.os72.protobuf360.InvalidProtocolBufferException {
      return new FireChanged(input, extensionRegistry);
    }
  };

  public static com.github.os72.protobuf360.Parser<FireChanged> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.os72.protobuf360.Parser<FireChanged> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.jmotor.metral.dto.FireChanged getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

