// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package org.jmotor.metral.dto;

public interface FireChangedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jmotor.metral.dto.FireChanged)
    com.github.os72.protobuf360.MessageOrBuilder {

  /**
   * <code>string entity = 1;</code>
   */
  java.lang.String getEntity();
  /**
   * <code>string entity = 1;</code>
   */
  com.github.os72.protobuf360.ByteString
      getEntityBytes();

  /**
   * <code>bytes identity = 2;</code>
   */
  com.github.os72.protobuf360.ByteString getIdentity();

  /**
   * <code>.org.jmotor.metral.dto.Operation operation = 3;</code>
   */
  int getOperationValue();
  /**
   * <code>.org.jmotor.metral.dto.Operation operation = 3;</code>
   */
  org.jmotor.metral.dto.Operation getOperation();

  /**
   * <code>int64 timestamp = 4;</code>
   */
  long getTimestamp();

  /**
   * <code>map&lt;string, bytes&gt; attributes = 5;</code>
   */
  int getAttributesCount();
  /**
   * <code>map&lt;string, bytes&gt; attributes = 5;</code>
   */
  boolean containsAttributes(
      java.lang.String key);
  /**
   * Use {@link #getAttributesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.github.os72.protobuf360.ByteString>
  getAttributes();
  /**
   * <code>map&lt;string, bytes&gt; attributes = 5;</code>
   */
  java.util.Map<java.lang.String, com.github.os72.protobuf360.ByteString>
  getAttributesMap();
  /**
   * <code>map&lt;string, bytes&gt; attributes = 5;</code>
   */

  com.github.os72.protobuf360.ByteString getAttributesOrDefault(
      java.lang.String key,
      com.github.os72.protobuf360.ByteString defaultValue);
  /**
   * <code>map&lt;string, bytes&gt; attributes = 5;</code>
   */

  com.github.os72.protobuf360.ByteString getAttributesOrThrow(
      java.lang.String key);
}
