// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package org.jmotor.metral.dto;

/**
 * Protobuf type {@code org.jmotor.metral.dto.Message}
 */
public  final class Message extends
    com.github.os72.protobuf360.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.jmotor.metral.dto.Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.github.os72.protobuf360.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    id_ = "";
    topic_ = "";
    payload_ = com.github.os72.protobuf360.ByteString.EMPTY;
  }

  @java.lang.Override
  public final com.github.os72.protobuf360.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Message(
      com.github.os72.protobuf360.CodedInputStream input,
      com.github.os72.protobuf360.ExtensionRegistryLite extensionRegistry)
      throws com.github.os72.protobuf360.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.github.os72.protobuf360.UnknownFieldSet.Builder unknownFields =
        com.github.os72.protobuf360.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            topic_ = s;
            break;
          }
          case 26: {

            payload_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.github.os72.protobuf360.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.github.os72.protobuf360.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.github.os72.protobuf360.Descriptors.Descriptor
      getDescriptor() {
    return org.jmotor.metral.dto.MetralMessages.internal_static_org_jmotor_metral_dto_Message_descriptor;
  }

  @java.lang.Override
  protected com.github.os72.protobuf360.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.jmotor.metral.dto.MetralMessages.internal_static_org_jmotor_metral_dto_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.jmotor.metral.dto.Message.class, org.jmotor.metral.dto.Message.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.github.os72.protobuf360.ByteString bs = 
          (com.github.os72.protobuf360.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   */
  public com.github.os72.protobuf360.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.github.os72.protobuf360.ByteString b = 
          com.github.os72.protobuf360.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.github.os72.protobuf360.ByteString) ref;
    }
  }

  public static final int TOPIC_FIELD_NUMBER = 2;
  private volatile java.lang.Object topic_;
  /**
   * <code>string topic = 2;</code>
   */
  public java.lang.String getTopic() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.github.os72.protobuf360.ByteString bs = 
          (com.github.os72.protobuf360.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      topic_ = s;
      return s;
    }
  }
  /**
   * <code>string topic = 2;</code>
   */
  public com.github.os72.protobuf360.ByteString
      getTopicBytes() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      com.github.os72.protobuf360.ByteString b = 
          com.github.os72.protobuf360.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      topic_ = b;
      return b;
    } else {
      return (com.github.os72.protobuf360.ByteString) ref;
    }
  }

  public static final int PAYLOAD_FIELD_NUMBER = 3;
  private com.github.os72.protobuf360.ByteString payload_;
  /**
   * <code>bytes payload = 3;</code>
   */
  public com.github.os72.protobuf360.ByteString getPayload() {
    return payload_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.github.os72.protobuf360.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.github.os72.protobuf360.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getTopicBytes().isEmpty()) {
      com.github.os72.protobuf360.GeneratedMessageV3.writeString(output, 2, topic_);
    }
    if (!payload_.isEmpty()) {
      output.writeBytes(3, payload_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.github.os72.protobuf360.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getTopicBytes().isEmpty()) {
      size += com.github.os72.protobuf360.GeneratedMessageV3.computeStringSize(2, topic_);
    }
    if (!payload_.isEmpty()) {
      size += com.github.os72.protobuf360.CodedOutputStream
        .computeBytesSize(3, payload_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.jmotor.metral.dto.Message)) {
      return super.equals(obj);
    }
    org.jmotor.metral.dto.Message other = (org.jmotor.metral.dto.Message) obj;

    boolean result = true;
    result = result && getId()
        .equals(other.getId());
    result = result && getTopic()
        .equals(other.getTopic());
    result = result && getPayload()
        .equals(other.getPayload());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + TOPIC_FIELD_NUMBER;
    hash = (53 * hash) + getTopic().hashCode();
    hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getPayload().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.jmotor.metral.dto.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.github.os72.protobuf360.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jmotor.metral.dto.Message parseFrom(
      java.nio.ByteBuffer data,
      com.github.os72.protobuf360.ExtensionRegistryLite extensionRegistry)
      throws com.github.os72.protobuf360.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jmotor.metral.dto.Message parseFrom(
      com.github.os72.protobuf360.ByteString data)
      throws com.github.os72.protobuf360.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jmotor.metral.dto.Message parseFrom(
      com.github.os72.protobuf360.ByteString data,
      com.github.os72.protobuf360.ExtensionRegistryLite extensionRegistry)
      throws com.github.os72.protobuf360.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jmotor.metral.dto.Message parseFrom(byte[] data)
      throws com.github.os72.protobuf360.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jmotor.metral.dto.Message parseFrom(
      byte[] data,
      com.github.os72.protobuf360.ExtensionRegistryLite extensionRegistry)
      throws com.github.os72.protobuf360.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jmotor.metral.dto.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.github.os72.protobuf360.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.jmotor.metral.dto.Message parseFrom(
      java.io.InputStream input,
      com.github.os72.protobuf360.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.github.os72.protobuf360.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.jmotor.metral.dto.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.github.os72.protobuf360.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.jmotor.metral.dto.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.github.os72.protobuf360.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.github.os72.protobuf360.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.jmotor.metral.dto.Message parseFrom(
      com.github.os72.protobuf360.CodedInputStream input)
      throws java.io.IOException {
    return com.github.os72.protobuf360.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.jmotor.metral.dto.Message parseFrom(
      com.github.os72.protobuf360.CodedInputStream input,
      com.github.os72.protobuf360.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.github.os72.protobuf360.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.jmotor.metral.dto.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.github.os72.protobuf360.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.jmotor.metral.dto.Message}
   */
  public static final class Builder extends
      com.github.os72.protobuf360.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.jmotor.metral.dto.Message)
      org.jmotor.metral.dto.MessageOrBuilder {
    public static final com.github.os72.protobuf360.Descriptors.Descriptor
        getDescriptor() {
      return org.jmotor.metral.dto.MetralMessages.internal_static_org_jmotor_metral_dto_Message_descriptor;
    }

    @java.lang.Override
    protected com.github.os72.protobuf360.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jmotor.metral.dto.MetralMessages.internal_static_org_jmotor_metral_dto_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.jmotor.metral.dto.Message.class, org.jmotor.metral.dto.Message.Builder.class);
    }

    // Construct using org.jmotor.metral.dto.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.github.os72.protobuf360.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.github.os72.protobuf360.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      topic_ = "";

      payload_ = com.github.os72.protobuf360.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.github.os72.protobuf360.Descriptors.Descriptor
        getDescriptorForType() {
      return org.jmotor.metral.dto.MetralMessages.internal_static_org_jmotor_metral_dto_Message_descriptor;
    }

    @java.lang.Override
    public org.jmotor.metral.dto.Message getDefaultInstanceForType() {
      return org.jmotor.metral.dto.Message.getDefaultInstance();
    }

    @java.lang.Override
    public org.jmotor.metral.dto.Message build() {
      org.jmotor.metral.dto.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.jmotor.metral.dto.Message buildPartial() {
      org.jmotor.metral.dto.Message result = new org.jmotor.metral.dto.Message(this);
      result.id_ = id_;
      result.topic_ = topic_;
      result.payload_ = payload_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.github.os72.protobuf360.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.github.os72.protobuf360.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.github.os72.protobuf360.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.github.os72.protobuf360.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.github.os72.protobuf360.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.github.os72.protobuf360.Message other) {
      if (other instanceof org.jmotor.metral.dto.Message) {
        return mergeFrom((org.jmotor.metral.dto.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.jmotor.metral.dto.Message other) {
      if (other == org.jmotor.metral.dto.Message.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getTopic().isEmpty()) {
        topic_ = other.topic_;
        onChanged();
      }
      if (other.getPayload() != com.github.os72.protobuf360.ByteString.EMPTY) {
        setPayload(other.getPayload());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.github.os72.protobuf360.CodedInputStream input,
        com.github.os72.protobuf360.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.jmotor.metral.dto.Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.github.os72.protobuf360.InvalidProtocolBufferException e) {
        parsedMessage = (org.jmotor.metral.dto.Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.github.os72.protobuf360.ByteString bs =
            (com.github.os72.protobuf360.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.github.os72.protobuf360.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.github.os72.protobuf360.ByteString b = 
            com.github.os72.protobuf360.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.github.os72.protobuf360.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setIdBytes(
        com.github.os72.protobuf360.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object topic_ = "";
    /**
     * <code>string topic = 2;</code>
     */
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (!(ref instanceof java.lang.String)) {
        com.github.os72.protobuf360.ByteString bs =
            (com.github.os72.protobuf360.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string topic = 2;</code>
     */
    public com.github.os72.protobuf360.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof String) {
        com.github.os72.protobuf360.ByteString b = 
            com.github.os72.protobuf360.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.github.os72.protobuf360.ByteString) ref;
      }
    }
    /**
     * <code>string topic = 2;</code>
     */
    public Builder setTopic(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      topic_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string topic = 2;</code>
     */
    public Builder clearTopic() {
      
      topic_ = getDefaultInstance().getTopic();
      onChanged();
      return this;
    }
    /**
     * <code>string topic = 2;</code>
     */
    public Builder setTopicBytes(
        com.github.os72.protobuf360.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      topic_ = value;
      onChanged();
      return this;
    }

    private com.github.os72.protobuf360.ByteString payload_ = com.github.os72.protobuf360.ByteString.EMPTY;
    /**
     * <code>bytes payload = 3;</code>
     */
    public com.github.os72.protobuf360.ByteString getPayload() {
      return payload_;
    }
    /**
     * <code>bytes payload = 3;</code>
     */
    public Builder setPayload(com.github.os72.protobuf360.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      payload_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes payload = 3;</code>
     */
    public Builder clearPayload() {
      
      payload_ = getDefaultInstance().getPayload();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.github.os72.protobuf360.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.github.os72.protobuf360.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.jmotor.metral.dto.Message)
  }

  // @@protoc_insertion_point(class_scope:org.jmotor.metral.dto.Message)
  private static final org.jmotor.metral.dto.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.jmotor.metral.dto.Message();
  }

  public static org.jmotor.metral.dto.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.github.os72.protobuf360.Parser<Message>
      PARSER = new com.github.os72.protobuf360.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.github.os72.protobuf360.CodedInputStream input,
        com.github.os72.protobuf360.ExtensionRegistryLite extensionRegistry)
        throws com.github.os72.protobuf360.InvalidProtocolBufferException {
      return new Message(input, extensionRegistry);
    }
  };

  public static com.github.os72.protobuf360.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.os72.protobuf360.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.jmotor.metral.dto.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

