// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package org.jmotor.metral.dto;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jmotor.metral.dto.Message)
    com.github.os72.protobuf360.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.github.os72.protobuf360.ByteString
      getIdBytes();

  /**
   * <code>string topic = 2;</code>
   */
  java.lang.String getTopic();
  /**
   * <code>string topic = 2;</code>
   */
  com.github.os72.protobuf360.ByteString
      getTopicBytes();

  /**
   * <code>bytes payload = 3;</code>
   */
  com.github.os72.protobuf360.ByteString getPayload();
}
