// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package org.jmotor.metral.dto;

/**
 * Protobuf enum {@code org.jmotor.metral.dto.Operation}
 */
public enum Operation
    implements com.github.os72.protobuf360.ProtocolMessageEnum {
  /**
   * <code>CREATE = 0;</code>
   */
  CREATE(0),
  /**
   * <code>DELETE = 1;</code>
   */
  DELETE(1),
  /**
   * <code>MODIFY = 2;</code>
   */
  MODIFY(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CREATE = 0;</code>
   */
  public static final int CREATE_VALUE = 0;
  /**
   * <code>DELETE = 1;</code>
   */
  public static final int DELETE_VALUE = 1;
  /**
   * <code>MODIFY = 2;</code>
   */
  public static final int MODIFY_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Operation valueOf(int value) {
    return forNumber(value);
  }

  public static Operation forNumber(int value) {
    switch (value) {
      case 0: return CREATE;
      case 1: return DELETE;
      case 2: return MODIFY;
      default: return null;
    }
  }

  public static com.github.os72.protobuf360.Internal.EnumLiteMap<Operation>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.github.os72.protobuf360.Internal.EnumLiteMap<
      Operation> internalValueMap =
        new com.github.os72.protobuf360.Internal.EnumLiteMap<Operation>() {
          public Operation findValueByNumber(int number) {
            return Operation.forNumber(number);
          }
        };

  public final com.github.os72.protobuf360.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.github.os72.protobuf360.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.github.os72.protobuf360.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.jmotor.metral.dto.MetralMessages.getDescriptor().getEnumTypes().get(0);
  }

  private static final Operation[] VALUES = values();

  public static Operation valueOf(
      com.github.os72.protobuf360.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Operation(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:org.jmotor.metral.dto.Operation)
}

